```{r}
library(readr)
library(dplyr)
library(ggplot2)
str(faithfuld)
head(faithfuld)
summary(faithfuld)
```

```{r}
missing_values <- sapply(faithfuld, function(x) sum(is.na(x)))
print(missing_values)
```

```{r}
# Visualize the data
# Histogram for numerical variables
num_vars <- sapply(faithfuld, is.numeric)
num_data <- faithfuld[, num_vars]
```

```{r}
# boxplot
ggplot(faithfuld, aes(x =waiting, y =density)) +
  geom_boxplot(fill = "orange", color = "black") +
  theme_minimal() +
  labs(title = "Boxplot of Humidity by Season", x= "waiting", y= "density")
```

```{r}
# Scatter plot to show the relationship between two numeric variables (replace 'temp' and 'humidity' with appropriate column names)
ggplot(faithfuld, aes(x = waiting, y = density)) +
  geom_point(color = "red") +
  theme_minimal() +
  labs(title = "Scatter Plot of faithfuld", x = "waiting", y = "density")
```

```{r}
# Time series plot for a variable over time (replace 'date' and 'temp' with appropriate column names)
ggplot(faithfuld, aes(x = waiting , y = density)) +
  geom_line(color = "blue") +
  theme_minimal() +
  labs(title = "faithfuld", x = "waiting", y = "density")
```
